/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package armory.file.sort

import spock.lang.Specification
//TODO - Proper testing
class LogSortSpec extends Specification {
    def "reading files from dir ignores files which don't match the naming pattern"() {}

    def "combining two files ignores lines which don't conform to the specification"() {}

    def "combing two files results in a sorted file"() {}

    //TODO - Additional test cases
}
